# coupledL2-verify
[tltest.config]
core                        = 0
core.tl_c                   = 0
core.tl_ul                  = 0
startup.cycle               = 0
maximum_cycle               = @VERIFY_MAX_CYCLE@
memory.enable               = 0
mmio.enable                 = 0
cmo.enable                  = 0

[tltest.logger]
verbose                     = 0
verbose.xact_fired          = 0
verbose.xact_sequenced      = 0
verbose.xact_data_complete  = 0
verbose.memory.axi_write    = 0
verbose.memory.axi_read     = 0
verbose.data_full           = 0
verbose.agent_debug         = 0